apiVersion: v1
kind: ConfigMap
metadata:
  name: anhlk5_configmap
data:
  DB_NAME: postgres
  DB_USER: anhlk5
  DB_HOST: anhlk5-psql-postgresql
  DB_PORT: 5432
---
apiVersion: v1
kind: Secret
metadata:
  name: anhlk5_secret
type: Opaque
data:
  DB_PASSWORD: YW5obGs1