apiVersion: apps/v1
kind: Deployment
metadata:
  name: coworking-test
  labels:
    name: coworking-test
spec:
  replicas: 1
  selector:
    matchLabels:
      service: coworking
  template:
    metadata:
      labels:
        service: coworking
    spec:
      containers:
      - name: coworking-test
        image: nginx
        imagePullPolicy: IfNotPresent